/**
 * Integration tests — lib/api-gitea
 *
 * Runs against the live Gitea instance.
 * Requires GITEA_URL and GITEA_TOKEN env vars.
 */

import { describe, it, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { createGiteaClient, GiteaApiError } from '../lib/api-gitea/index'
import type { GiteaClient } from '../lib/api-gitea/index'

const GITEA_URL = process.env.GITEA_URL || 'http://localhost:3300'
const GITEA_TOKEN = process.env.GITEA_TOKEN || ''

describe('lib/api-gitea', () => {
  let gitea: GiteaClient

  before(() => {
    if (!GITEA_TOKEN) {
      console.log('⚠ GITEA_TOKEN not set — skipping integration tests')
      return
    }
    gitea = createGiteaClient(GITEA_URL, GITEA_TOKEN)
  })

  // ─── Users ───────────────────────────────────────────────────

  describe('users', () => {
    it('should get authenticated user', async () => {
      if (!GITEA_TOKEN) return
      const me = await gitea.users.me()
      assert.ok(me.id, 'user should have an id')
      assert.ok(me.login, 'user should have a login')
    })
  })

  // ─── Repos ───────────────────────────────────────────────────

  describe('repos', () => {
    it('should list user repos', async () => {
      if (!GITEA_TOKEN) return
      const repos = await gitea.repos.list({ limit: 5 })
      assert.ok(Array.isArray(repos), 'should return array')
      if (repos.length > 0) {
        assert.ok(repos[0].name, 'repo should have a name')
        assert.ok(repos[0].full_name, 'repo should have full_name')
        assert.ok(repos[0].owner, 'repo should have owner')
      }
    })

    it('should get a specific repo', async () => {
      if (!GITEA_TOKEN) return
      const repo = await gitea.repos.get('idea', 'gigi')
      assert.equal(repo.name, 'gigi')
      assert.ok(repo.id, 'repo should have an id')
    })

    it('should list branches', async () => {
      if (!GITEA_TOKEN) return
      const branches = await gitea.repos.listBranches('idea', 'gigi')
      assert.ok(Array.isArray(branches), 'should return array')
      assert.ok(branches.some(b => b.name === 'main'), 'should have main branch')
    })

    it('should list labels', async () => {
      if (!GITEA_TOKEN) return
      const labels = await gitea.repos.listLabels('idea', 'gigi')
      assert.ok(Array.isArray(labels), 'should return array')
      if (labels.length > 0) {
        assert.ok(labels[0].name, 'label should have a name')
      }
    })
  })

  // ─── Issues ──────────────────────────────────────────────────

  describe('issues', () => {
    let testIssueNumber: number | null = null

    it('should list issues', async () => {
      if (!GITEA_TOKEN) return
      const issues = await gitea.issues.list('idea', 'gigi', { limit: 5 })
      assert.ok(Array.isArray(issues), 'should return array')
      if (issues.length > 0) {
        assert.ok(issues[0].number, 'issue should have a number')
        assert.ok(issues[0].title, 'issue should have a title')
      }
    })

    it('should get a specific issue', async () => {
      if (!GITEA_TOKEN) return
      const issue = await gitea.issues.get('idea', 'gigi', 56)
      assert.equal(issue.number, 56)
      assert.ok(issue.title, 'issue should have a title')
      assert.ok(Array.isArray(issue.labels), 'should have labels array')
    })

    it('should create an issue and comment on it', async () => {
      if (!GITEA_TOKEN) return
      const issue = await gitea.issues.create('idea', 'gigi', {
        title: '[test] api-gitea integration test',
        body: 'Auto-generated by api-gitea integration test. Safe to delete.',
      })
      assert.ok(issue.number, 'created issue should have a number')
      assert.equal(issue.title, '[test] api-gitea integration test')
      testIssueNumber = issue.number

      // Comment on it
      const comment = await gitea.issues.createComment('idea', 'gigi', issue.number, 'Test comment from api-gitea')
      assert.ok(comment.id, 'comment should have an id')
      assert.equal(comment.body, 'Test comment from api-gitea')
    })

    after(async () => {
      // Clean up test issue by closing it
      if (testIssueNumber && GITEA_TOKEN) {
        await gitea.issues.edit('idea', 'gigi', testIssueNumber, { state: 'closed' })
      }
    })
  })

  // ─── Pulls ───────────────────────────────────────────────────

  describe('pulls', () => {
    it('should list pull requests', async () => {
      if (!GITEA_TOKEN) return
      const prs = await gitea.pulls.list('idea', 'gigi', { limit: 5 })
      assert.ok(Array.isArray(prs), 'should return array')
    })
  })

  // ─── Orgs ────────────────────────────────────────────────────

  describe('orgs', () => {
    it('should list user orgs', async () => {
      if (!GITEA_TOKEN) return
      const orgs = await gitea.orgs.list()
      assert.ok(Array.isArray(orgs), 'should return array')
    })

    it('should get org by name', async () => {
      if (!GITEA_TOKEN) return
      const org = await gitea.orgs.get('idea')
      assert.equal(org.name, 'idea')
    })

    it('should list org repos', async () => {
      if (!GITEA_TOKEN) return
      const repos = await gitea.orgs.listRepos('idea')
      assert.ok(Array.isArray(repos), 'should return array')
      assert.ok(repos.some(r => r.name === 'gigi'), 'should include gigi repo')
    })
  })

  // ─── Error Handling ──────────────────────────────────────────

  describe('errors', () => {
    it('should throw GiteaApiError on 404', async () => {
      if (!GITEA_TOKEN) return
      try {
        await gitea.repos.get('idea', 'nonexistent-repo-99999')
        assert.fail('should have thrown')
      } catch (err) {
        assert.ok(err instanceof GiteaApiError, 'should be GiteaApiError')
        assert.ok(err.isNotFound, 'should be not found')
        assert.equal(err.status, 404)
      }
    })

    it('should throw GiteaApiError on bad auth', async () => {
      if (!GITEA_TOKEN) return // need a reachable Gitea instance
      const bad = createGiteaClient(GITEA_URL, 'invalid-token-xxx')
      try {
        await bad.users.me()
        assert.fail('should have thrown')
      } catch (err) {
        assert.ok(err instanceof GiteaApiError, 'should be GiteaApiError')
        assert.ok(err.isUnauthorized, 'should be unauthorized')
      }
    })
  })
})
