name: Build and Deploy Gigi
on:
  push:
    branches: [main]

env:
  REGISTRY: 192.168.1.80:3000
  IMAGE: idea/gigi
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  DEPLOY_HOST: 192.168.1.110

jobs:
  build:
    runs-on: ubuntu-latest-utils
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Build on cluster (arm64)
        run: |
          rsync -az --exclude=.git --exclude=node_modules . root@${{ env.DEPLOY_HOST }}:/tmp/gigi-build/
          ssh root@${{ env.DEPLOY_HOST }} "
            cd /tmp/gigi-build
            docker build \
              -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} \
              -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest \
              .
            echo '${{ secrets.REGISTRY_TOKEN }}' | docker login ${{ env.REGISTRY }} -u ${{ github.repository_owner }} --password-stdin
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
            rm -rf /tmp/gigi-build"

      - name: Create Docker secrets
        run: |
          ssh root@${{ env.DEPLOY_HOST }} "
            echo '${{ secrets.SSH_PRIVATE_KEY_GIGI }}' | docker secret create gigi_ssh_key - 2>/dev/null || true"

      - name: Deploy service
        run: |
          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}"
          ssh root@${{ env.DEPLOY_HOST }} "
            docker stack rm idea-biancifiore-gigi 2>/dev/null; sleep 5
            printf '%s\n' \
              'version: \"3.9\"' \
              'services:' \
              '  gigi:' \
              '    image: ${IMAGE_TAG}' \
              '    environment:' \
              '      - DATABASE_URL=postgresql://gigi:${{ secrets.DB_PASSWORD }}@postgres:5432/gigi' \
              '    secrets:' \
              '      - gigi_ssh_key' \
              '    networks:' \
              '      - databases_default' \
              '      - http-entry_default' \
              '    deploy:' \
              '      mode: replicated' \
              '      replicas: 1' \
              '      update_config:' \
              '        order: start-first' \
              '        failure_action: rollback' \
              '      restart_policy:' \
              '        condition: on-failure' \
              '        delay: 5s' \
              '        max_attempts: 3' \
              '    healthcheck:' \
              '      test: [\"CMD-SHELL\", \"curl -f http://localhost:3000/health || exit 1\"]' \
              '      interval: 30s' \
              '      timeout: 10s' \
              '      retries: 3' \
              '      start_period: 40s' \
              'secrets:' \
              '  gigi_ssh_key:' \
              '    external: true' \
              'networks:' \
              '  databases_default:' \
              '    external: true' \
              '  http-entry_default:' \
              '    external: true' \
              > /tmp/gigi-compose.yml
            docker stack deploy -c /tmp/gigi-compose.yml --with-registry-auth idea-biancifiore-gigi
            rm /tmp/gigi-compose.yml"

      - name: Deploy Caddy config
        uses: http://192.168.1.80:3000/idea/deploy-site@main
        with:
          caddy_file: Caddyfile
          ssh_user: root
          swarm_host: 192.168.1.110
