name: Build and Deploy Dev
on:
  push:
    branches: [main]

env:
  REGISTRY: prod.gigi.local
  IMAGE: gigi/gigi
  DEPLOY_HOST: 192.168.1.110
  SSH_OPTS: "-i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new"

jobs:
  build:
    runs-on: ubuntu-latest-utils
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Login to Gitea registry
        run: |
          docker login ${{ env.REGISTRY }} \
            -u gigi-admin -p "${{ secrets.REGISTRY_TOKEN }}"

      - name: Build AIO image
        run: |
          docker build -f Dockerfile.aio \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:dev-latest \
            .

      - name: Push to registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:dev-latest

      - name: Deploy dev
        run: |
          ssh $SSH_OPTS m@${{ env.DEPLOY_HOST }} "
            sudo docker service update \
              --image ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} \
              --with-registry-auth gigi-dev_gigi"

      - name: Verify dev health
        run: |
          sleep 30
          ssh $SSH_OPTS m@${{ env.DEPLOY_HOST }} \
            "curl -sf http://localhost:3000/health" || echo "Health check pending"
