name: Build and Deploy Gigi
on:
  push:
    branches: [main]

env:
  REGISTRY: 192.168.1.80:3000
  IMAGE: ideabile/gigi
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

jobs:
  build:
    runs-on: ubuntu-latest-utils
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name multiarch --driver docker-container \
            --driver-opt network=host \
            --config /dev/stdin --use <<'EOF'
          [registry."192.168.1.80:3000"]
            http = true
            insecure = true
          EOF
          docker buildx inspect --bootstrap

      - name: Build and push image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest \
            --push .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Update service
        run: |
          ssh root@192.168.1.110 \
            "docker service update \
              --image ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest \
              --with-registry-auth \
              ideabile-biancifiore-gigi_gigi"
