name: Integration Tests
on:
  push:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npx vitest run --project integration
        env:
          CI: true
          # The dev database — only runs after merge to main
          TEST_DATABASE_URL: postgresql://gigi_test:gigi_test@postgres:5432/gigi_test
